// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmHDUx9G2nnfjCHBx-rtPmEBrvUiu_YqY',
    appId: '1:914362024742:web:277a80778c1d54252337e7',
    messagingSenderId: '914362024742',
    projectId: 'yeekai-de9a8',
    authDomain: 'yeekai-de9a8.firebaseapp.com',
    storageBucket: 'yeekai-de9a8.firebasestorage.app',
    measurementId: 'G-FBSZPXP4Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuRmprfFglmOKeoSuwhghX2kQdua9QkwY',
    appId: '1:914362024742:android:f02122372f09c3b92337e7',
    messagingSenderId: '914362024742',
    projectId: 'yeekai-de9a8',
    storageBucket: 'yeekai-de9a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQIY1CHSYxavpCbd-WjZg56Gu-nhdnvb4',
    appId: '1:914362024742:ios:6202214b629cc5672337e7',
    messagingSenderId: '914362024742',
    projectId: 'yeekai-de9a8',
    storageBucket: 'yeekai-de9a8.firebasestorage.app',
    iosBundleId: 'com.sn.atr.yeekai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQIY1CHSYxavpCbd-WjZg56Gu-nhdnvb4',
    appId: '1:914362024742:ios:eaae29486c8579852337e7',
    messagingSenderId: '914362024742',
    projectId: 'yeekai-de9a8',
    storageBucket: 'yeekai-de9a8.firebasestorage.app',
    iosBundleId: 'com.example.yeebusFilthyMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmHDUx9G2nnfjCHBx-rtPmEBrvUiu_YqY',
    appId: '1:914362024742:web:2aaea2b69c745b042337e7',
    messagingSenderId: '914362024742',
    projectId: 'yeekai-de9a8',
    authDomain: 'yeekai-de9a8.firebaseapp.com',
    storageBucket: 'yeekai-de9a8.firebasestorage.app',
    measurementId: 'G-H0Z28CC2QN',
  );
}
